# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.valid_time import ValidTime  # noqa: F401,E501
from swagger_server import util


class Authorize(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, door_right: List[int]=None, right_plan: List[int]=None, valid_time: ValidTime=None):  # noqa: E501
        """Authorize - a model defined in Swagger

        :param door_right: The door_right of this Authorize.  # noqa: E501
        :type door_right: List[int]
        :param right_plan: The right_plan of this Authorize.  # noqa: E501
        :type right_plan: List[int]
        :param valid_time: The valid_time of this Authorize.  # noqa: E501
        :type valid_time: ValidTime
        """
        self.swagger_types = {
            'door_right': List[int],
            'right_plan': List[int],
            'valid_time': ValidTime
        }

        self.attribute_map = {
            'door_right': 'doorRight',
            'right_plan': 'RightPlan',
            'valid_time': 'validTime'
        }

        self._door_right = door_right
        self._right_plan = right_plan
        self._valid_time = valid_time

    @classmethod
    def from_dict(cls, dikt) -> 'Authorize':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Authorize of this Authorize.  # noqa: E501
        :rtype: Authorize
        """
        return util.deserialize_model(dikt, cls)

    @property
    def door_right(self) -> List[int]:
        """Gets the door_right of this Authorize.


        :return: The door_right of this Authorize.
        :rtype: List[int]
        """
        return self._door_right

    @door_right.setter
    def door_right(self, door_right: List[int]):
        """Sets the door_right of this Authorize.


        :param door_right: The door_right of this Authorize.
        :type door_right: List[int]
        """

        self._door_right = door_right

    @property
    def right_plan(self) -> List[int]:
        """Gets the right_plan of this Authorize.


        :return: The right_plan of this Authorize.
        :rtype: List[int]
        """
        return self._right_plan

    @right_plan.setter
    def right_plan(self, right_plan: List[int]):
        """Sets the right_plan of this Authorize.


        :param right_plan: The right_plan of this Authorize.
        :type right_plan: List[int]
        """

        self._right_plan = right_plan

    @property
    def valid_time(self) -> ValidTime:
        """Gets the valid_time of this Authorize.


        :return: The valid_time of this Authorize.
        :rtype: ValidTime
        """
        return self._valid_time

    @valid_time.setter
    def valid_time(self, valid_time: ValidTime):
        """Sets the valid_time of this Authorize.


        :param valid_time: The valid_time of this Authorize.
        :type valid_time: ValidTime
        """

        self._valid_time = valid_time
